/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as PedidoErroRouteImport } from './routes/pedido.erro'
import { Route as PedidoPendenteRouteImport } from './routes/pedido.pendente'
import { Route as PedidoSucessoRouteImport } from './routes/pedido.sucesso'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoErroRoute = PedidoErroRouteImport.update({
  id: '/pedido/erro',
  path: '/pedido/erro',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoPendenteRoute = PedidoPendenteRouteImport.update({
  id: '/pedido/pendente',
  path: '/pedido/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoSucessoRoute = PedidoSucessoRouteImport.update({
  id: '/pedido/sucesso',
  path: '/pedido/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/produtos'
    | '/categoria/$slug'
    | '/pedido/erro'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/produtos'
    | '/categoria/$slug'
    | '/pedido/erro'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/produtos'
    | '/categoria/$slug'
    | '/pedido/erro'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ProdutosRoute: typeof ProdutosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PedidoErroRoute: typeof PedidoErroRoute
  PedidoPendenteRoute: typeof PedidoPendenteRoute
  PedidoSucessoRoute: typeof PedidoSucessoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/erro': {
      id: '/pedido/erro'
      path: '/pedido/erro'
      fullPath: '/pedido/erro'
      preLoaderRoute: typeof PedidoErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/pendente': {
      id: '/pedido/pendente'
      path: '/pedido/pendente'
      fullPath: '/pedido/pendente'
      preLoaderRoute: typeof PedidoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/sucesso': {
      id: '/pedido/sucesso'
      path: '/pedido/sucesso'
      fullPath: '/pedido/sucesso'
      preLoaderRoute: typeof PedidoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ProdutosRoute: ProdutosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PedidoErroRoute: PedidoErroRoute,
  PedidoPendenteRoute: PedidoPendenteRoute,
  PedidoSucessoRoute: PedidoSucessoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
