/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as PedidoErroRouteImport } from './routes/pedido.erro'
import { Route as PedidoPendenteRouteImport } from './routes/pedido.pendente'
import { Route as PedidoSucessoRouteImport } from './routes/pedido.sucesso'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminPedidosIndexRouteImport } from './routes/_authenticated/admin.pedidos.index'
import { Route as AuthenticatedAdminPedidosIdRouteImport } from './routes/_authenticated/admin.pedidos.$id'
import { Route as ApiPublicStoreImagesNameRouteImport } from './routes/api/public/store-images.$name'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoErroRoute = PedidoErroRouteImport.update({
  id: '/pedido/erro',
  path: '/pedido/erro',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoPendenteRoute = PedidoPendenteRouteImport.update({
  id: '/pedido/pendente',
  path: '/pedido/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoSucessoRoute = PedidoSucessoRouteImport.update({
  id: '/pedido/sucesso',
  path: '/pedido/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/admin/banners',
    path: '/admin/banners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/admin/categorias',
    path: '/admin/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/admin/clientes',
    path: '/admin/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPedidosIndexRoute =
  AuthenticatedAdminPedidosIndexRouteImport.update({
    id: '/admin/pedidos/',
    path: '/admin/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPedidosIdRoute =
  AuthenticatedAdminPedidosIdRouteImport.update({
    id: '/admin/pedidos/$id',
    path: '/admin/pedidos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStoreImagesNameRoute =
  ApiPublicStoreImagesNameRouteImport.update({
    id: '/api/public/store-images/$name',
    path: '/api/public/store-images/$name',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/store-images/$name': typeof ApiPublicStoreImagesNameRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/admin/pedidos/': typeof AuthenticatedAdminPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/store-images/$name': typeof ApiPublicStoreImagesNameRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/store-images/$name': typeof ApiPublicStoreImagesNameRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/_authenticated/admin/pedidos/': typeof AuthenticatedAdminPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/produtos'
    | '/admin/login'
    | '/categoria/$slug'
    | '/pedido/erro'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produto/$slug'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/produtos'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/api/public/store-images/$name'
    | '/api/public/webhooks/mercadopago'
    | '/admin/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/produtos'
    | '/admin/login'
    | '/categoria/$slug'
    | '/pedido/erro'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produto/$slug'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/produtos'
    | '/admin'
    | '/admin/pedidos/$id'
    | '/api/public/store-images/$name'
    | '/api/public/webhooks/mercadopago'
    | '/admin/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/produtos'
    | '/admin/login'
    | '/categoria/$slug'
    | '/pedido/erro'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produto/$slug'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pedidos/$id'
    | '/api/public/store-images/$name'
    | '/api/public/webhooks/mercadopago'
    | '/_authenticated/admin/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ProdutosRoute: typeof ProdutosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PedidoErroRoute: typeof PedidoErroRoute
  PedidoPendenteRoute: typeof PedidoPendenteRoute
  PedidoSucessoRoute: typeof PedidoSucessoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicStoreImagesNameRoute: typeof ApiPublicStoreImagesNameRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/erro': {
      id: '/pedido/erro'
      path: '/pedido/erro'
      fullPath: '/pedido/erro'
      preLoaderRoute: typeof PedidoErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/pendente': {
      id: '/pedido/pendente'
      path: '/pedido/pendente'
      fullPath: '/pedido/pendente'
      preLoaderRoute: typeof PedidoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/sucesso': {
      id: '/pedido/sucesso'
      path: '/pedido/sucesso'
      fullPath: '/pedido/sucesso'
      preLoaderRoute: typeof PedidoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pedidos/': {
      id: '/_authenticated/admin/pedidos/'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pedidos/$id': {
      id: '/_authenticated/admin/pedidos/$id'
      path: '/admin/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/store-images/$name': {
      id: '/api/public/store-images/$name'
      path: '/api/public/store-images/$name'
      fullPath: '/api/public/store-images/$name'
      preLoaderRoute: typeof ApiPublicStoreImagesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPedidosIdRoute: typeof AuthenticatedAdminPedidosIdRoute
  AuthenticatedAdminPedidosIndexRoute: typeof AuthenticatedAdminPedidosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPedidosIdRoute: AuthenticatedAdminPedidosIdRoute,
  AuthenticatedAdminPedidosIndexRoute: AuthenticatedAdminPedidosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BuscaRoute: BuscaRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ProdutosRoute: ProdutosRoute,
  AdminLoginRoute: AdminLoginRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PedidoErroRoute: PedidoErroRoute,
  PedidoPendenteRoute: PedidoPendenteRoute,
  PedidoSucessoRoute: PedidoSucessoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicStoreImagesNameRoute: ApiPublicStoreImagesNameRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
